export const UserDetails = [{ name: 'Pcc1', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc2', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc3', email: 'Pcc1@gmail.com', status: 'Unhealthy' },
    { name: 'Pcc4', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc5', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc6', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc7', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc8', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc9', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc10', email: 'Pcc1@gmail.com', status: 'Unhealthy' },
    { name: 'Pcc11', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc12', email: 'Pcc1@gmail.com', status: 'Danger' },
    { name: 'Pcc13', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc14', email: 'Pcc1@gmail.com', status: 'Healthy' },
    { name: 'Pcc15', email: 'Pcc1@gmail.com', status: 'Healthy' },
    {name:'Pcc16',email:'Pcc1@gmail.com',status:'Danger'}]